# -*- coding: utf-8 -*-
{'application': True,
 'assets': {'web.assets_backend': ['med_iot_command_center/static/src/css/backend_grey_fix.css',
                                   'med_iot_command_center/static/src/css/settings_admin_control.css',
                                   'med_iot_command_center/static/src/css/patient_match_pic2.css',
                                   'med_iot_command_center/static/src/js/personal_greeting.js',
                                   'med_iot_command_center/static/src/js/dashboard.js',
                                   'med_iot_command_center/static/src/js/alert_group_toggle.js',
                                   'med_iot_command_center/static/src/js/logout_redirect_home_safe.js',
                                   'med_iot_command_center/static/src/xml/dashboard.xml',
                                   'med_iot_command_center/static/src/scss/dashboard.scss',
                                   'med_iot_command_center/static/src/css/dashboard.css',
                                   'med_iot_command_center/static/src/css/patient.css',
                                   'med_iot_command_center/static/src/css/admin_dashboard.css',
                                   'med_iot_command_center/static/src/css/mediot_menu_color.css',
                                   'med_iot_command_center/static/src/css/mediot_compact_header_source.css'],
            'web.assets_frontend': ['med_iot_command_center/static/src/js/why_mediot_polish.js',
                                    'med_iot_command_center/static/src/js/auth_portal.js',
                                    'med_iot_command_center/static/src/js/landing_counters.js',
                                    'med_iot_command_center/static/src/css/why_mediot_polish.css',
                                    'med_iot_command_center/static/src/css/auth_portal.css'],
            'web.assets_web': ['med_iot_command_center/static/src/js/dashboard.js',
                               'med_iot_command_center/static/src/js/logout_redirect_home_safe.js',
                               'med_iot_command_center/static/src/xml/dashboard.xml',
                               'med_iot_command_center/static/src/scss/dashboard.scss',
                               'med_iot_command_center/static/src/css/dashboard.css',
                               'med_iot_command_center/static/src/css/patient.css',
                               'med_iot_command_center/static/src/css/admin_dashboard.css',
                               'med_iot_command_center/static/src/css/mediot_menu_color.css',
                               'med_iot_command_center/static/src/css/mediot_compact_header_source.css']},
 'author': 'Farah Mehrez',
 'category': 'Healthcare',
 'data': ['security/security.xml',
          'security/record_rules.xml',
          'security/ir.model.access.csv',
          'data/sequence.xml',
          'data/alert_email_cron.xml',
          'data/patient_demo.xml',
          'views/patient_views.xml',
          'views/vital_reading_views.xml',
          'views/alert_views.xml',
          'views/device_views.xml',
          'views/settings_views.xml',
          'views/auth_pages.xml',
          'views/login_template.xml',
          'views/signup_template.xml',
          'views/admin_dashboard_views.xml',
          'views/menus.xml',
          'reports/patient_medical_report.xml'],
 'depends': ['base', 'web', 'mail', 'auth_signup', 'website'],
 'images': ['static/description/icon.png'],
 'installable': True,
 'license': 'LGPL-3',
 'name': 'MedIoT Command Center',
 'summary': 'Doctor dashboard for real-time patient monitoring + alerts + history',
 'version': '19.0.1.0.0'}
